---
title: "Data Viz"
author: "Jalene LaMontagne"
date: "3/1/2021"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{R}
  library(leaflet)
  library(dplyr)
  library(tidyr)
  library(ggplot2)
  library(DT)
  library(scales) # install.packages("scales")
```

```{R}
data_url <- "https://knb.ecoinformatics.org/knb/d1/mn/v2/object/urn%3Auuid%3Af119a05b-bbe7-4aea-93c6-85434dcb1c5e"
esc <- tryCatch(
    read.csv("data/escapement.csv", stringsAsFactors = FALSE),
    error=function(cond) {
        message(paste("Escapement file does not seem to exist, so get it from the KNB."))
        esc <- read.csv(url(data_url, method = "libcurl"), stringsAsFactors = FALSE)
        return(esc)
    }
)
head(esc)
```

```{R}
annual_esc <- esc %>% 
  separate(sampleDate, c("Year", "Month", "Day"), sep = "-") %>% 
  mutate(Year = as.numeric(Year)) %>% 
  group_by(Species, SASAP.Region, Year) %>% 
  summarize(escapement = sum(DailyCount)) %>% 
  filter(Species %in% c("Chinook", "Sockeye", "Chum", "Coho", "Pink"))

head(annual_esc)
  
```

```{R}
#ggplot(annual_esc, aes(x = Species, y = escapement)) +
#  geom_col(fill = "blue")

#ggplot(annual_esc, aes(x = Species, y = escapement, fill = Species)) +
#  geom_col()

ggplot(annual_esc, aes(x = Species, y = escapement, fill = SASAP.Region)) +
  geom_col()

```

```{R}
# Make a fancier plot, only on a subset of the data
kodiak_esc <- annual_esc %>%
  filter(SASAP.Region == "Kodiak")

#ggplot(kodiak_esc, aes(x=Year, y=escapement, color = Species)) +
 #geom_line() +
 #geom_point() +
 #ylab("Escapement") +
 #ggtitle("Kodiak Salmon Escapement")+
 #theme_classic()+
 #theme(legend.position = "bottom", legend.title = element_blank())

#Can make a special theme with the last two lines (graph is the same as above)
my_theme <- theme_classic()+
  theme(legend.position = "bottom", legend.title = element_blank())

ggplot(kodiak_esc, aes(x=Year, y=escapement, color = Species)) +
  geom_line() +
  geom_point() +
  scale_y_continuous(labels = comma)+
  ylab("Escapement") +
  ggtitle("Kodiak Salmon Escapement")+
  my_theme

```

```{R}
my_plot<-ggplot(annual_esc, aes(x=Year, y=escapement, color = Species)) +
  geom_line() +
  geom_point() +
  scale_y_continuous(labels = comma)+
  facet_wrap(~ SASAP.Region, scales = "free_y", ncol = 2)
  ylab("Escapement") +
  my_theme
  
  ggsave("chart.png", my_plot)

```

```{r}
#Make an interactive table - that's even searchable
locations <-esc %>%
  distinct(Location, Latitude, Longitude) %>%
  drop_na()

datatable(locations)
```

```{r}
leaflet(locations) %>%
  addTiles() %>%
  addMarkers(ln = ~Longitude, lat = ~ Latitude, popup = ~ Location)

```