---
title: "Spatial Analysis with sf"
author: "Jalene LaMontagne"
date: "3/3/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(sf)
library(dplyr)
library(ggplot2)
library(leaflet)
library(scales)
library(ggmap)
```

```{r}
## Read in shapefile using sf
#ak_regions <- read_sf("training_lamontagne/shapefiles/ak_regions_simp.shp")

ak_regions <- read_sf("shapefiles/ak_regions_simp.shp")
plot(ak_regions)
```

```{r}
class(ak_regions)
head(ak_regions)
st_crs(ak_regions)

ak_regions_3338 <- ak_regions %>%
  st_transform(crs = 3338)

st_crs(ak_regions_3338)

plot(ak_regions_3338)
```

```{r}

ak_regions_3338 %>%
  select(region)
```

```{r}
ak_regions_3338 %>%
  filter(region == "Southeast")
```

```{r}
#add in the population data
pop <- read.csv("shapefiles/alaska_population.csv")
```

```{r}
#note: crs is the Coordinate Reference System
#if lat/long - it is likely WGS84 - the most commonly used
#remove = FALSE keeps the lat lng columns around
pop_4326 <- st_as_sf(pop, 
                  coords = c('lng', 'lat'),
                  crs = 4326,
                  remove = FALSE)

head(pop_4326)

# Note, the code below CANNOT just be combined with the code above.
# crs above is what the crs is in (not what you want it to be in)
# THEN, you can transform it to what you want it to be in

pop_3338 <-st_transform(pop_4326, crs = 3338)
```

```{r}
#Doing a spatial join - ?st_join gives us all the options
pop_joined <- st_join(pop_3338, ak_regions_3338, join = st_within)
head(pop_joined)
```

```{r}
pop_region <- pop_joined %>%
  #as.data.frame() %>% 
  group_by(region) %>%
  summarise(total_pop = sum(population), .groups = 'drop')

head(pop_region)
plot(pop_region) #not what we want - it's still for each city - do next block
```

```{r}
pop_region <- pop_joined %>%
  as.data.frame() %>% 
  group_by(region) %>%
  summarise(total_pop = sum(population), .groups = 'drop')

head(pop_region)
```

```{r}
#now to a join to have the populations assigned at the region scale
pop_region_3338 <- left_join(ak_regions_3338, pop_region)
plot(pop_region_3338)
```

```{r}
#Do this for the management area (and get rid of interior lines with do_union = T) 
pop_mgmt_338 <- pop_region_3338 %>% 
  group_by(mgmt_area) %>% 
  summarize(total_pop = sum(total_pop), do_union = TRUE) 

plot(pop_mgmt_338)
```

```{r}
# Now - visualize using ggplot - this is a little different from the notes
ggplot() +
  geom_sf(data = pop_region_3338, aes(fill = total_pop)) +  #even just to here gives a map
  theme_bw()+
  labs(fill = "Total Population") +
  scale_fill_continuous(low = "khaki", high = "firebrick", labels = comma)
```

```{r}
#Get rivers data to add
rivers_3338 <- read_sf("shapefiles/ak_rivers_simp.shp")
st_crs(rivers_3338)
```

```{r}
# Now - add the rivers (this could have been done all above, I just broke it up)
# Also, some code to rescale the size of the streams - looked bad without it
ggplot() +
  geom_sf(data = pop_region_3338, aes(fill = total_pop)) +
  geom_sf(data = rivers_3338, aes(size = StrOrder), color = "black") +
  geom_sf(data = pop_3338, aes(), size = .5) +
  theme_bw() +
  labs(fill = "Total Population") +
  scale_fill_continuous(low = "khaki", high =  "firebrick", labels = comma) +
scale_size(range = c(0.01, 0.2), guide = FALSE) #The range set based on guess & check
```

Psudo-mercator: 3857

```{r}
#going to use ggmap
pop_3857 <- pop_3338 %>%
  st_transform(crs = 3857)
```

```{r}
#There are issues with the bounding box, this fixes it

# Define a function to fix the bbox to be in EPSG:3857
# See https://github.com/dkahle/ggmap/issues/160#issuecomment-397055208
ggmap_bbox_to_3857 <- function(map) {
  if (!inherits(map, "ggmap")) stop("map must be a ggmap object")
  # Extract the bounding box (in lat/lon) from the ggmap to a numeric vector, 
  # and set the names to what sf::st_bbox expects:
  map_bbox <- setNames(unlist(attr(map, "bb")), 
                       c("ymin", "xmin", "ymax", "xmax"))
  
  # Coonvert the bbox to an sf polygon, transform it to 3857, 
  # and convert back to a bbox (convoluted, but it works)
  bbox_3857 <- st_bbox(st_transform(st_as_sfc(st_bbox(map_bbox, crs = 4326)), 3857))
  
  # Overwrite the bbox of the ggmap object with the transformed coordinates 
  attr(map, "bb")$ll.lat <- bbox_3857["ymin"]
  attr(map, "bb")$ll.lon <- bbox_3857["xmin"]
  attr(map, "bb")$ur.lat <- bbox_3857["ymax"]
  attr(map, "bb")$ur.lon <- bbox_3857["xmax"]
  map
}
```

```{r}
#set the bounding box
bbox <-c(-170, 52, -130, 64)
ak_map <- get_stamenmap(bbox, zoom = 4)
ak_map_3857 <- ggmap_bbox_to_3857(ak_map)   #this grabs 6 tiles
```

```{r}
ggmap(ak_map_3857) + 
  geom_sf(data = pop_3857, aes(color = population), inherit.aes = F) +
  scale_color_continuous(low = "khaki", high =  "firebrick", labels = comma)
```